version: '3.8'

services:
  dev-db:
    image: postgres:17
    container_name: dev-db
    restart: always
    environment:
      POSTGRES_USER: gregory
      POSTGRES_PASSWORD: password
      POSTGRES_DB: formation-chat
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
